Test GAMS on CI withmacos-latest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,71 +11,87 @@ on:
   workflow_dispatch:
 
 jobs:
-  CI:
-    runs-on: ubuntu-latest
-
+  Gams-test:
+    runs-on: macos-latest
     steps:
-      - uses: actions/checkout@v3
-        with:
-          path: times-excel-reader
+      - run: |
+          curl https://d37drm4t2jghv5.cloudfront.net/distributions/44.1.0/macosx/osx_x64_64_sfx.exe -o osx_x64_64_sfx.exe
+          mkdir GAMS
+          pushd  GAMS
+          ../osx_x64_64_sfx.exe
+          export PATH=$PATH:$(pwd)/gams44.1_osx_x64_sfx
+          popd
+          mkdir -p $HOME/Library/Application\ Support/GAMS
+          echo "$GAMS_LICENSE" > $HOME/Library/Application\ Support/GAMS/gamslice.txt
+          gamslib trnsport
+          gams trnsport
+        env:
+          GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
+  # CI:
+  #   runs-on: ubuntu-latest
 
-      - name: Install packages
-        working-directory: times-excel-reader
-        run: |
-          python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         path: times-excel-reader
 
-      - name: Check code formatting
-        working-directory: times-excel-reader
-        run: |
-          pre-commit install
-          pre-commit run --all-files
+  #     - name: Install packages
+  #       working-directory: times-excel-reader
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
-      - uses: jakebailey/pyright-action@v1 # Type checking
-        with:
-          version: 1.1.304
+  #     - name: Check code formatting
+  #       working-directory: times-excel-reader
+  #       run: |
+  #         pre-commit install
+  #         pre-commit run --all-files
 
-      # ---------- Prepare ETSAP Demo models
+  #     - uses: jakebailey/pyright-action@v1 # Type checking
+  #       with:
+  #         version: 1.1.304
 
-      - uses: actions/checkout@v3
-        with:
-          repository: olejandro/demos-dd
-          path: times-excel-reader/benchmarks/dd
+  #     # ---------- Prepare ETSAP Demo models
 
-      - uses: actions/checkout@v3
-        with:
-          repository: olejandro/demos-xlsx
-          path: times-excel-reader/benchmarks/xlsx
-          token: ${{ secrets.GH_PAT_DEMOS_XLSX }}
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         repository: olejandro/demos-dd
+  #         path: times-excel-reader/benchmarks/dd
 
-      # ---------- Prepare TIMES Ireland Model
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         repository: olejandro/demos-xlsx
+  #         path: times-excel-reader/benchmarks/xlsx
+  #         token: ${{ secrets.GH_PAT_DEMOS_XLSX }}
 
-      # We add this model as the directory `ireland` under `benchmarks/{xlsx,dd}/`
-      # so that the run_benchmarks.py script runs this model too
-      - uses: actions/checkout@v3
-        with:
-          repository: samwebster/times-ireland-model
-          path: times-excel-reader/benchmarks/xlsx/Ireland
+  #     # ---------- Prepare TIMES Ireland Model
 
-      - uses: actions/checkout@v3
-        with:
-          repository: olejandro/times-ireland-model_gams
-          path: times-excel-reader/benchmarks/dd/Ireland
+  #     # We add this model as the directory `ireland` under `benchmarks/{xlsx,dd}/`
+  #     # so that the run_benchmarks.py script runs this model too
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         repository: samwebster/times-ireland-model
+  #         path: times-excel-reader/benchmarks/xlsx/Ireland
 
-      # ---------- Run tool, check for regressions
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         repository: olejandro/times-ireland-model_gams
+  #         path: times-excel-reader/benchmarks/dd/Ireland
 
-      - name: Run tool on all benchmarks
-        working-directory: times-excel-reader
-        # Use tee to also save the output to out.txt so that the summary table can be
-        # printed again in the next step.
-        # Save the return code to retcode.txt so that the next step can fail the action
-        # if run_benchmarks.py failed.
-        run: |
-          (python utils/run_benchmarks.py benchmarks.yml --verbose | tee out.txt; \
-            echo ${PIPESTATUS[0]} > retcode.txt)
+  #     # ---------- Run tool, check for regressions
 
-      - name: Print summary
-        working-directory: times-excel-reader
-        run: |
-          sed -n '/Benchmark *Time.*Accuracy/h;//!H;$!d;x;//p' out.txt
-          exit $(cat retcode.txt)
+  #     - name: Run tool on all benchmarks
+  #       working-directory: times-excel-reader
+  #       # Use tee to also save the output to out.txt so that the summary table can be
+  #       # printed again in the next step.
+  #       # Save the return code to retcode.txt so that the next step can fail the action
+  #       # if run_benchmarks.py failed.
+  #       run: |
+  #         (python utils/run_benchmarks.py benchmarks.yml --verbose | tee out.txt; \
+  #           echo ${PIPESTATUS[0]} > retcode.txt)
+
+  #     - name: Print summary
+  #       working-directory: times-excel-reader
+  #       run: |
+  #         sed -n '/Benchmark *Time.*Accuracy/h;//!H;$!d;x;//p' out.txt
+  #         exit $(cat retcode.txt)
