CI now checks for regressions and runs GAMS

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -86,34 +86,30 @@ jobs:
         env:
           GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
 
-      # ---------- Run tool, compare GDX outputs
+      # ---------- Run tool, check for regressions
 
-      - name: Run tool on benchmarks, compare GDX outputs
+      - name: Run tool on all benchmarks
         working-directory: times-excel-reader
+        # Use tee to also save the output to out.txt so that the summary table can be
+        # printed again in the next step.
+        # Save the return code to retcode.txt so that the next step can fail the action
+        # if run_benchmarks.py failed.
         run: |
           export PATH=$PATH:$GITHUB_WORKSPACE/GAMS/gams44.1_linux_x64_64_sfx
-          python utils/run_benchmarks.py benchmarks.yml --dd --times_dir $GITHUB_WORKSPACE/TIMES_model
+          (python utils/run_benchmarks.py benchmarks.yml \
+              --dd --times_dir $GITHUB_WORKSPACE/TIMES_model \
+              --verbose \
+              | tee out.txt; \
+            echo ${PIPESTATUS[0]} > retcode.txt)
 
-      - uses: actions/upload-artifact@v3
+      - name: Print summary
+        working-directory: times-excel-reader
+        run: |
+          sed -n '/Benchmark *Time.*Accuracy/h;//!H;$!d;x;//p' out.txt
+          exit $(cat retcode.txt)
+
+      - name: Upload output folder as artifact
+        uses: actions/upload-artifact@v3
         with:
           name: dd-outputs
           path: times-excel-reader/benchmarks/out/
-
-      # # ---------- Run tool, check for regressions
-      # TODO re-enable after merging --dd run above with csv comparison below
-
-      # - name: Run tool on all benchmarks
-      #   working-directory: times-excel-reader
-      #   # Use tee to also save the output to out.txt so that the summary table can be
-      #   # printed again in the next step.
-      #   # Save the return code to retcode.txt so that the next step can fail the action
-      #   # if run_benchmarks.py failed.
-      #   run: |
-      #     (python utils/run_benchmarks.py benchmarks.yml --verbose | tee out.txt; \
-      #       echo ${PIPESTATUS[0]} > retcode.txt)
-
-      # - name: Print summary
-      #   working-directory: times-excel-reader
-      #   run: |
-      #     sed -n '/Benchmark *Time.*Accuracy/h;//!H;$!d;x;//p' out.txt
-      #     exit $(cat retcode.txt)
