Bring back CI tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,128 +53,128 @@ jobs:
           # Install the built wheel file to imitiate users installing from PyPI:
           python -m pip install --no-index --find-links=dist xl2times
 
-      # - name: Run unit tests
-      #   working-directory: xl2times
-      #   run: |
-      #     source .venv/bin/activate
-      #     pytest
+      - name: Run unit tests
+        working-directory: xl2times
+        run: |
+          source .venv/bin/activate
+          pytest
 
-      # # ---------- Prepare ETSAP Demo models
+      # ---------- Prepare ETSAP Demo models
 
-      # - uses: actions/checkout@v3
-      #   with:
-      #     repository: etsap-TIMES/TIMES_model
-      #     path: TIMES_model
-      #     ref: ${{ env.REF_TIMES_model }}
+      - uses: actions/checkout@v3
+        with:
+          repository: etsap-TIMES/TIMES_model
+          path: TIMES_model
+          ref: ${{ env.REF_TIMES_model }}
 
-      # - uses: actions/checkout@v3
-      #   with:
-      #     repository: olejandro/demos-dd
-      #     path: xl2times/benchmarks/dd
-      #     ref: ${{ env.REF_demos-dd }}
+      - uses: actions/checkout@v3
+        with:
+          repository: olejandro/demos-dd
+          path: xl2times/benchmarks/dd
+          ref: ${{ env.REF_demos-dd }}
 
-      # - uses: actions/checkout@v3
-      #   with:
-      #     repository: olejandro/demos-xlsx
-      #     path: xl2times/benchmarks/xlsx
-      #     ref: ${{ env.REF_demos-xlsx }}
-      #     token: ${{ secrets.GH_PAT_DEMOS_XLSX }}
+      - uses: actions/checkout@v3
+        with:
+          repository: olejandro/demos-xlsx
+          path: xl2times/benchmarks/xlsx
+          ref: ${{ env.REF_demos-xlsx }}
+          token: ${{ secrets.GH_PAT_DEMOS_XLSX }}
 
-      # # ---------- Prepare TIMES Ireland Model
+      # ---------- Prepare TIMES Ireland Model
 
-      # # We add this model as the directory `ireland` under `benchmarks/{xlsx,dd}/`
-      # # so that the run_benchmarks.py script runs this model too
-      # - uses: actions/checkout@v3
-      #   with:
-      #     repository: esma-cgep/tim
-      #     path: xl2times/benchmarks/xlsx/Ireland
-      #     ref: ${{ env.REF_tim }}
+      # We add this model as the directory `ireland` under `benchmarks/{xlsx,dd}/`
+      # so that the run_benchmarks.py script runs this model too
+      - uses: actions/checkout@v3
+        with:
+          repository: esma-cgep/tim
+          path: xl2times/benchmarks/xlsx/Ireland
+          ref: ${{ env.REF_tim }}
 
-      # - uses: actions/checkout@v3
-      #   with:
-      #     repository: esma-cgep/tim-gams
-      #     path: xl2times/benchmarks/dd/Ireland
-      #     ref: ${{ env.REF_tim-gams }}
+      - uses: actions/checkout@v3
+        with:
+          repository: esma-cgep/tim-gams
+          path: xl2times/benchmarks/dd/Ireland
+          ref: ${{ env.REF_tim-gams }}
 
-      # # ---------- Install GAMS
+      # ---------- Install GAMS
 
-      # - name: Install GAMS
-      #   env:
-      #     GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
-      #   if: ${{ env.GAMS_LICENSE != '' }}
-      #   run: |
-      #     curl https://d37drm4t2jghv5.cloudfront.net/distributions/44.1.0/linux/linux_x64_64_sfx.exe -o linux_x64_64_sfx.exe
-      #     chmod +x linux_x64_64_sfx.exe
-      #     mkdir GAMS
-      #     pushd  GAMS
-      #     ../linux_x64_64_sfx.exe > /dev/null && echo Successfully installed GAMS
-      #     export PATH=$PATH:$(pwd)/gams44.1_linux_x64_64_sfx
-      #     popd
-      #     echo Creating license file at $HOME/.local/share/GAMS
-      #     mkdir -p $HOME/.local/share/GAMS
-      #     echo "$GAMS_LICENSE" > $HOME/.local/share/GAMS/gamslice.txt
-      #     ls -l $HOME/.local/share/GAMS/
+      - name: Install GAMS
+        env:
+          GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
+        if: ${{ env.GAMS_LICENSE != '' }}
+        run: |
+          curl https://d37drm4t2jghv5.cloudfront.net/distributions/44.1.0/linux/linux_x64_64_sfx.exe -o linux_x64_64_sfx.exe
+          chmod +x linux_x64_64_sfx.exe
+          mkdir GAMS
+          pushd  GAMS
+          ../linux_x64_64_sfx.exe > /dev/null && echo Successfully installed GAMS
+          export PATH=$PATH:$(pwd)/gams44.1_linux_x64_64_sfx
+          popd
+          echo Creating license file at $HOME/.local/share/GAMS
+          mkdir -p $HOME/.local/share/GAMS
+          echo "$GAMS_LICENSE" > $HOME/.local/share/GAMS/gamslice.txt
+          ls -l $HOME/.local/share/GAMS/
 
-      # # ---------- Run tool, check for regressions
+      # ---------- Run tool, check for regressions
 
-      # - name: Restore XLSX cache directory from cache
-      #   id: cache
-      #   uses: actions/cache/restore@v4
-      #   with:
-      #     path: ~/.cache/xl2times
-      #     # Cache key is refs of the input xlsx repos, since that's what is cached
-      #     key: ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-${{ env.REF_tim }}-${{ env.CACHE_KEY }}
-      #     # If we can't find the exact key for the TIM repo, still use the cache if the demos repo ref matches
-      #     restore-keys: |
-      #       ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-${{ env.REF_tim }}-
-      #       ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-
-      #       ${{ runner.os }}-py-${{ env.PY_VERSION }}-
+      - name: Restore XLSX cache directory from cache
+        id: cache
+        uses: actions/cache/restore@v4
+        with:
+          path: ~/.cache/xl2times
+          # Cache key is refs of the input xlsx repos, since that's what is cached
+          key: ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-${{ env.REF_tim }}-${{ env.CACHE_KEY }}
+          # If we can't find the exact key for the TIM repo, still use the cache if the demos repo ref matches
+          restore-keys: |
+            ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-${{ env.REF_tim }}-
+            ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-
+            ${{ runner.os }}-py-${{ env.PY_VERSION }}-
 
-      # - name: Run tool on all benchmarks
-      #   env:
-      #     GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
-      #   if: ${{ env.GAMS_LICENSE != '' }}
-      #   working-directory: xl2times
-      #   # Use tee to also save the output to out.txt so that the summary table can be
-      #   # printed again in the next step.
-      #   # Save the return code to retcode.txt so that the next step can fail the action
-      #   run: |
-      #     source .venv/bin/activate
-      #     export PATH=$PATH:$GITHUB_WORKSPACE/GAMS/gams44.1_linux_x64_64_sfx
-      #     (python utils/run_benchmarks.py benchmarks.yml \
-      #         --dd --times_dir $GITHUB_WORKSPACE/TIMES_model \
-      #         --verbose \
-      #         | tee out.txt; \
-      #       echo ${PIPESTATUS[0]} > retcode.txt)
+      - name: Run tool on all benchmarks
+        env:
+          GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
+        if: ${{ env.GAMS_LICENSE != '' }}
+        working-directory: xl2times
+        # Use tee to also save the output to out.txt so that the summary table can be
+        # printed again in the next step.
+        # Save the return code to retcode.txt so that the next step can fail the action
+        run: |
+          source .venv/bin/activate
+          export PATH=$PATH:$GITHUB_WORKSPACE/GAMS/gams44.1_linux_x64_64_sfx
+          (python utils/run_benchmarks.py benchmarks.yml \
+              --dd --times_dir $GITHUB_WORKSPACE/TIMES_model \
+              --verbose \
+              | tee out.txt; \
+            echo ${PIPESTATUS[0]} > retcode.txt)
 
-      # - name: Run CSV-only regression tests (no GAMS license)
-      #   env:
-      #     GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
-      #   if: ${{ env.GAMS_LICENSE == '' }}
-      #   working-directory: xl2times
-      #   # Run without --dd flag if GAMS license secret doesn't exist.
-      #   # Useful for testing for (CSV) regressions in forks before creating PRs.
-      #   run: |
-      #     source .venv/bin/activate
-      #     export PATH=$PATH:$GITHUB_WORKSPACE/GAMS/gams44.1_linux_x64_64_sfx
-      #     (python utils/run_benchmarks.py benchmarks.yml \
-      #         --times_dir $GITHUB_WORKSPACE/TIMES_model \
-      #         --verbose \
-      #         | tee out.txt; \
-      #     echo ${PIPESTATUS[0]} > retcode.txt)
+      - name: Run CSV-only regression tests (no GAMS license)
+        env:
+          GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
+        if: ${{ env.GAMS_LICENSE == '' }}
+        working-directory: xl2times
+        # Run without --dd flag if GAMS license secret doesn't exist.
+        # Useful for testing for (CSV) regressions in forks before creating PRs.
+        run: |
+          source .venv/bin/activate
+          export PATH=$PATH:$GITHUB_WORKSPACE/GAMS/gams44.1_linux_x64_64_sfx
+          (python utils/run_benchmarks.py benchmarks.yml \
+              --times_dir $GITHUB_WORKSPACE/TIMES_model \
+              --verbose \
+              | tee out.txt; \
+          echo ${PIPESTATUS[0]} > retcode.txt)
 
-      # - name: Print summary
-      #   working-directory: xl2times
-      #   run: |
-      #     sed -n '/Benchmark *Time.*Accuracy/h;//!H;$!d;x;//p' out.txt
-      #     exit $(cat retcode.txt)
+      - name: Print summary
+        working-directory: xl2times
+        run: |
+          sed -n '/Benchmark *Time.*Accuracy/h;//!H;$!d;x;//p' out.txt
+          exit $(cat retcode.txt)
 
-      # - uses: actions/cache/save@v4
-      #   # Save the cache even if the regression tests fail
-      #   if: always() && !steps.cache-restore.outputs.cache-hit
-      #   with:
-      #     path: ~/.cache/xl2times
-      #     key: ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-${{ env.REF_tim }}-${{ env.CACHE_KEY }}
+      - uses: actions/cache/save@v4
+        # Save the cache even if the regression tests fail
+        if: always() && !steps.cache-restore.outputs.cache-hit
+        with:
+          path: ~/.cache/xl2times
+          key: ${{ runner.os }}-py-${{ env.PY_VERSION }}-${{ env.REF_demos-xlsx }}-${{ env.REF_tim }}-${{ env.CACHE_KEY }}
 
       # ---------- Upload package to PyPI on release
 
